### ISSUE TITLE
hi ertagh have you push issue to BOX86?the programmer wants to get more details

### ISSUE THREAD

**Issue by SoraKasvgano** [ertagh/teamspeak3-server-arm#10]
hi ertagh have you push issue to BOX86?the programmer wants to get more details

you can contact him via Discord

https://discord.gg/6jPVJJdqtu 

box86 tag.....

he wants to fix the problem

**Comment by ertagh** [comment]
Box86 is now fully working! See [#16](https://github.com/ertagh/teamspeak3-server-arm/issues/16#issuecomment-817670656)
