### ISSUE TITLE
How to get Authorization code after first start?

### ISSUE THREAD

**Issue by sackiorg** [ertagh/teamspeak3-server-arm#18]
Hi, how  to get the Authorization code after starting the server to administrate the new Teamspeak Server. Can you add this information to your good Howto.

Report from my side: Works good at Raspberry Pi4 4 GB with Raspbian 10 Buster x86. - Server starts, but i need the Code to give my User Admin privilegs

Many Thanks and how can i donate you?

**Comment by sackiorg** [comment]
https://github.com/ertagh/teamspeak3-server-arm/issues/14

**Comment by ertagh** [comment]
Hi there
That's  actually a great idea! 
I added a new section within the readme that adresses how to get the server admin privilege key.
(During that I actually updated the containers to the latest server and box86 version)

Also good to know it runs well on your setup!

Never thought about donations until now... So I added a button to Ko-fi. Feel free to donate!

Greetings and thanks for using!
