### ISSUE TITLE
how about add X86 support?

### ISSUE THREAD

**Issue by SoraKasvgano** [ertagh/teamspeak3-server-arm#19]
how about add X86 support ,
it would be convenient to deploy ts3 server with this docker image on all platform

**Comment by ertagh** [comment]
I can look into it in the following weeks!
Never thought about it, because there are plenty of options already available

**Comment by ertagh** [comment]
Hi again!
Finally got time and implemented x86, x64 support with the current update!
Now it should be possible to switch easily between the different architectures.

Hope you like it!
