### ISSUE TITLE
unable to exec /teamspeak/ts3server_minimal_runscript.sh: No such file or directory

### ISSUE THREAD

**Issue by samondlee** [ertagh/teamspeak3-server-arm#2]
I run it with armbian and docker

docker run -d --name TeamSpeak3_Server -e TIME_ZONE=Europe/Berlin -p 9987:9987/udp -p 10011:10011/tcp -p 30033:30033/tcp -v root:/teamspeak/save/ ertagh/teamspeak3-server:latest 

but it says 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Updating timezone to Europe/Berlin,
,
Current default time zone: 'Europe/Berlin',
Local time is now:      Tue Jun  2 09:03:50 CEST 2020.,
Universal Time is now:  Tue Jun  2 07:03:50 UTC 2020.,
,
-----------------------------------------------------------------------,
TeamSpeak updater:,
-----------------------------------------------------------------------,
Internet connectivity check failed! No update was done.,
Starting TeamSpeak 3 Server..,
s6-applyuidgid: fatal: unable to exec /teamspeak/ts3server_minimal_runscript.sh: No such file or directory,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,

**Comment by ertagh** [comment]
The important line for you is the first one after the "TeamSpeak updater:". As its says, there was a problem while checking the internet connectivity. 
Please check if your container has access to the internet and if you can resolve hostnames.

**Comment by samondlee** [comment]
> The important line for you is the first one after the "TeamSpeak updater:". As its says, there was a problem while checking the internet connectivity.
> Please check if your container has access to the internet and if you can resolve hostnames.

i am sure docker's host has internet connection,and container has ip such as 172.0.x.x...and how to check if the container has internet connection?

emmm,did it have GFW banned  sites' resource?
it would be better have downloaded ts3 server files in next version....

**Comment by ertagh** [comment]
Ouh sorry didn't thought about the GFW. The internet connectivity check is actually a ping to google.com. I will change that in the next version, so it should work as expected.
Expect the update later this day!

The container had a predownloaded version of ts3 before I rewrote many of the code. But I will look into an option to make an installation/update with a manually downloaded file.

**Comment by ertagh** [comment]
I pushed an update to docker hub a few minutes ago. 
I hope the new update fixes your problem as well. Please let me know!

**Comment by samondlee** [comment]
> I pushed an update to docker hub a few minutes ago.
> I hope the new update fixes your problem as well. Please let me know!

latest update looks works well...but it downlod @ a very low speed ,and very grateful for u to update the docker with  a lighting speed....


log:

TeamSpeak updater:,
-----------------------------------------------------------------------,
Update available! 0 -> 3.12.1,
Downloading new version: 3.12.1,


Even TS official site get a very poor connect in Our reigion....
After i use V2RAY on my  router ,the server looks start to download.


and it would be nicely, if u can provide me this docker's  ts3 server install package, I can offer u a mirror(ChinaTelecom 163) and  Russian mirrorfor users who are located in Asia.

**Comment by samondlee** [comment]
Wow! it works fine....
My server is ARMBIAN 5.60 user-built Debian GNU/Linux 9 (stretch) 4.18.7-aml-s905x  
ARMv8 Processor rev 4 with 2 G RAM.... called phicomm N1 only cost lower than 10 dollars(including ship cost)

here is probe:http://n1.uss.moe:9988/yh.php
and my ts is  IPV4/IPV6 :  n1.uss.moe:9987

**Comment by samondlee** [comment]
I have posted a guide on China's largest router firmware community to promote this docker image,let them give stars...hope to help more people have their own TS3 server....

https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=4034139

**Comment by ertagh** [comment]
I'm just using the standard 32Bit server for linux. The container automatically downloads the latest release from teamspeak.com during the first run.
On their official website they say that mirroring is forbidden without their written consent...
Just wondering: Is the connection to docker hub in china actually fast (or faster than to teamspeak.com)? 
I'm thinking about releasing a seperate image with a predownloaded version of teamspeak already included...

And thanks a lot for sharing my little teamspeak project! That helps a lot!

**Comment by samondlee** [comment]
> I'm just using the standard 32Bit server for linux. The container automatically downloads the latest release from teamspeak.com during the first run.
> On their official website they say that mirroring is forbidden without their written consent...
> Just wondering: Is the connection to docker hub in china actually fast (or faster than to teamspeak.com)?
> I'm thinking about releasing a seperate image with a predownloaded version of teamspeak already included...
> 
> And thanks a lot for sharing my little teamspeak project! That helps a lot!

docker hub is slowly in CN,but we have docker hub mirror, such as Aliyun's mirror.... https://dev.aliyun.com

**Comment by samondlee** [comment]
thanks a lot,issue closed
