### ISSUE TITLE
Running on Raspberry Pi Zero (ARMv6)

### ISSUE THREAD

**Issue by Madave94** [ertagh/teamspeak3-server-arm#20]
Thank you for the very nice implementation.

I was wondering if it is possible to run the Server on a Raspberry Pi Zero as well?

I tried running it but recieved a warning that ARM32v6 is not the right version for either the ARM32v7 as well as the ARM32v8 image. Would it be possible to run teamspeak on the zero?

**Comment by ertagh** [comment]
Well, at the beginning of the project I looked into it and there was some problem I couldn't solve.
But if I remember correctly it was related to QEMU, so maybe with Box86 it will run...
I will look into it!

**Comment by ertagh** [comment]
With the current update I've added ARM32v5 support.
Now it is possible to run a TeamSpeak Server on RPi Zeroes.

I'm actually using QEMU for the emulation again, but it just works. Performance wise, well the server actually takes a few minutes to start up and the CPU usage will be hovering about 13% while the server is idling..
So it may only be suitable for a small group of people.

**Comment by Madave94** [comment]
Thanks for implementing the feature. I gonna try it later.
