### ISSUE TITLE
Performance of emulation

### ISSUE THREAD

**Issue by ex0nuss** [ertagh/teamspeak3-server-arm#21]
Hi there,

I am thinking about migrating my TS3 server to your image (RPI4). Currently I am running it on a x86 instance.

How is the performance of emulation? 
Did you do any tests on how many users can use the server simultaneously?

Thx and regards!

**Comment by ertagh** [comment]
Hi there,
I never did any tests on how many users can use the server simultaneously..
The performance of emulation actually differs between the version.
Box86 should have the better performance compared to QEMU.
Worth Mentioning: QEMU only runs on one single core!
Greetings!
