### ISSUE TITLE
Is there a Compose File?

### ISSUE THREAD

**Issue by ghost** [ertagh/teamspeak3-server-arm#22]
Is it possible to use this with Portainer and install the Container about a Compose file?

Thank you :-).

**Comment by ertagh** [comment]
Hi there,

I'm actually using Portainer and docker-compose myself..
So I quickly modified my own compose file to match the run example shown in the readme.

Change to your liking!
Hope that helped

```shell
version: '3'

services:
 teamspeak:
  container_name: TeamSpeak3_Server
  image: ertagh/teamspeak3-server:arm32v7-latest-box86
  environment:
   - TS_UPDATE=1
   - TIME_ZONE=Europe/Berlin
  ports:
   - "9987:9987/udp"
   - "10011:10011/tcp"
   - "30033:30033/tcp"
  volumes:
   - "{path}:/teamspeak/save/"

networks:
 default:
  external:
   name: bridged-network
```

**Comment by ghost** [comment]
Thank you, Ticket can be closed :-).
