### ISSUE TITLE
Is it possible to use box64 on ARM64?

### ISSUE THREAD

**Issue by TheXAHTEP** [ertagh/teamspeak3-server-arm#23]
Is it possible to use box64 on ARM64 or x86_64 Teamspeak server binaries uses some x86 libs?

**Comment by TheXAHTEP** [comment]
After some binwalking I think that's possible

binwalk ts3server
0             0x0             ELF, 64-bit LSB executable, AMD x86-64, version 1 (SYSV)

libts3_ssh.so
0             0x0             ELF, 64-bit LSB shared object, AMD x86-64, version 1 (SYSV)

libts3db_mariadb.so
0             0x0             ELF, 64-bit LSB shared object, AMD x86-64, version 1 (SYSV)

libts3db_postgresql.so
0             0x0             ELF, 64-bit LSB shared object, AMD x86-64, version 1 (SYSV)

libts3db_sqlite3.so
0             0x0             ELF, 64-bit LSB shared object, AMD x86-64, version 1 (SYSV)

tsdns/tsdnsserver
0             0x0             ELF, 64-bit LSB executable, AMD x86-64, version 1 (SYSV)

redist/libmariadb.so.2
0             0x0             ELF, 64-bit LSB shared object, AMD x86-64, version 1 (SYSV)

**Comment by ertagh** [comment]
Thanks for already looking into it!
I will evaluate and test it in the next 1-2 weeks!

**Comment by SoraKasvgano** [comment]
https://github.com/ptitSeb/box64

aha,i found someone posted this issue ahead of mine.......

looking forward to see box64 version too

**Comment by ertagh** [comment]
It actually took me longer until I had time to look into it.

With the latest update I added an arm64v8 image with box64!

**Comment by TheXAHTEP** [comment]
It works great! Thanks for your work!
