### ISSUE TITLE
Update Teamspeak without losing settings

### ISSUE THREAD

**Issue by ghost** [ertagh/teamspeak3-server-arm#24]
Is it possible to update/recreate the teamspeak container about portainer without losing all the created settings/channels?

Thank you :-)...

**Comment by ertagh** [comment]
Just tested it myself to give no wrong answer..
It's possible as long as `/teamspeak/save` is saved outside the container.
As long as this folder is inside a volume there is no problem..

**Comment by ghost** [comment]
Will try it, thank you ;-)!
