### ISSUE TITLE
Docker image for pterodactyl

### ISSUE THREAD

**Issue by zVapor-Dev** [ertagh/teamspeak3-server-arm#25]
Hi! Is it possible to get a docket image for the pterodactyl panel? If so is this publicly available?

**Comment by QuintenQVD0** [comment]
WORKDIR must be set the /home/container

and there must be a entrypoint.sh
https://pterodactyl.io/community/config/eggs/creating_a_custom_image.html

**Comment by zVapor-Dev** [comment]
Can you tell me how? I’m really inexperienced with this stuff

**Comment by QuintenQVD0** [comment]
read the docs and ask help off this outhor
