### ISSUE TITLE
Step by step guide? Auto booting ?

### ISSUE THREAD

**Issue by capsload2** [ertagh/teamspeak3-server-arm#26]
Hey,

i have no idea how to start the server automatically after booting my raspberry zero w 2.

docker was created, server runs.

Just didnt come back online after a reboot/ or / boot.

**Comment by ertagh** [comment]
Hi there,
well, the default setting of the container is that it has to be started manually after rebooting.

I guess you are using the `docker run` command?
In that case just add `--restart unless-stopped` to the command.
Should look like this:
`docker run -d --name TeamSpeak3_Server --restart unless-stopped -e TS_UPDATE=1 [...]`

Hope that helps!

**Comment by capsload2** [comment]
Thanks!

If i restart the VPS it will automatically start the docker?

**Comment by ertagh** [comment]
Yes! The container will always restart, unless you stopped it manually.
