### ISSUE TITLE
arm v6 (raspberry wh / w) first generation

### ISSUE THREAD

**Issue by capsload2** [ertagh/teamspeak3-server-arm#28]
Hello,

it seems that the first generation of Raspberry Zero W and Zero WH can't install the Server using the latest docker:

`sudo docker run -d --name TeamSpeak3_Server --restart unless-stopped -e TS_UPDATE=1 -e TIME_ZONE=Europe/Berlin -p 9987:9987/udp -p 10011:10011/tcp -p 30033:30033/tcp -v /home/teamspeak/:/teamspeak/save/ ertagh/teamspeak3-server:latest`

`WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested`

**Comment by ertagh** [comment]
It should work without any problem.
It seems the wrong image gets requested.

`sudo docker run -d --name TeamSpeak3_Server --restart unless-stopped -e TS_UPDATE=1 -e TIME_ZONE=Europe/Berlin -p 9987:9987/udp -p 10011:10011/tcp -p 30033:30033/tcp -v /home/teamspeak/:/teamspeak/save/ ertagh/teamspeak3-server:arm32v5-latest-qemu`

Try actually requesting the arm32v5 version directly.
Please report back if there are still any problems

**Comment by capsload2** [comment]
Worked like a charm!

Just for clarification,

if i want to install box on my Raspberry Zero WH, what would be the command/repo?

Thanks!

**Comment by ertagh** [comment]
Box version is only available for arm32v7 and arm64v8. 
So unfortunately QEMU is the only way to go on the original Raspberry Pi Zero.

**Comment by capsload2** [comment]
Thanks!
