### ISSUE TITLE
Special version of Teamspeak3

### ISSUE THREAD

**Issue by SoraKasvgano** [ertagh/teamspeak3-server-arm#31]
Dude,no offence, i just found an unlimited ts server version and install script, would you like to add that special version?XD

server: http://rpi48g.s0r4.com:9988/ts3crack/teamspeak3-server_linux_x86.zip
client(<3.2.0 only):http://rpi48g.s0r4.com:9988/ts3crack/teamspeak3client.zip
install script:http://rpi48g.s0r4.com:9988/ts3crack/installv3.sh
patch for windows client:http://rpi48g.s0r4.com:9988/ts3crack/clientpatch.rar
readme:http://rpi48g.s0r4.com:9988/ts3crack/readme.txt

**Comment by ertagh** [comment]
I could look at it and prepare a extra version where you would be able to run that version if you are interested in that?

**Comment by capsload2** [comment]
Its a cracked version ( illegal ) just for your notes

**Comment by SoraKasvgano** [comment]
> I could look at it and prepare a extra version where you would be able to run that version if you are interested in that?

raspbian(arm) or debian（x86）?

idk
