### ISSUE TITLE
one more suggestion

### ISSUE THREAD

**Issue by SoraKasvgano** [ertagh/teamspeak3-server-arm#4]
when you make X86-ARM docker files ,you can try to use https://github.com/ptitSeb/box86 it's more efficient .....and it can use GPU directly.....

**Comment by ertagh** [comment]
I looked into it today and it seems to work.
Will test it the next days.. expect an update on that matter very soon!

**Comment by ertagh** [comment]
I actually switched over to Box86 for the arm32v7 images. 
Thanks for the hint!
