### ISSUE TITLE
serveradmin password

### ISSUE THREAD

**Issue by t1n00** [ertagh/teamspeak3-server-arm#40]
Hi,
your docker is very nice! But i need to get the serveradmin password. I got the token via logfile but no serveradmin password.... Do you have a guide to reset this password?
(i am new to linux and quemu....)
TY

**Comment by ertagh** [comment]
Sorry for the late reply.

The serveradmin password gets shown if you create a new server.

So you execute the run command first and after that just use `docker logs -f  <container_name>`. Inside these logs the password will be shown but teamspeak will not log them. 
In your case `docker logs <container_name>` will be the only chance you may still find it at the very top of the log.

Hope this will help anyone that may has the same problem as you.
