### ISSUE TITLE
Add TS3 Manager or a similar tool

### ISSUE THREAD

**Issue by daendir** [ertagh/teamspeak3-server-arm#42]
How about adding TS3 Manager or a similar tool natively to the image or making an image with that tool separately?

Right now I'm using the TS5 Client and it doesn't have all the tools to properly manage the server, forcing me to install the TS3 client as well

**Comment by ertagh** [comment]
Hi there!

in my opinion adding TS3 Manager to the image natively would bloat it unnecessary. Especially for people that don't need/want it.
So especially thinking about the 'docker way' of doing it.. it wouln't be a good idea either.

I actually didn't know about TS3 Manager until now and had to search for it and found that they have a native docker image that should work on arm. Just wondering therefore... is there anything wrong with that?
