### ISSUE TITLE
I want to know how to copy a server installed on x86 to my new arm

### ISSUE THREAD

**Issue by qrst1ks** [ertagh/teamspeak3-server-arm#47]
Hello
I want to know how to copy a server installed on x86 to my new arm
My {path} is /home/teamspeak/ 
What files should I copy over and what files should I back up in the future

Thanks

**Comment by ertagh** [comment]
Hi!
I think there are many ways how you can do this.
I would probably do the following:

1.  Start the arm teamspeak and let it initialize everything
2. Stop the arm teamspeak server
3. Go into your {path} directory
4. Replace every file that is inside this directory with the corresponding file from your x86 server

That should probably do the trick...
