### ISSUE TITLE
TS3 Server Query Port Issue [ISSUE]

### ISSUE THREAD

**Issue by solidus1983** [ertagh/teamspeak3-server-arm#5]
Hi although i have set the Query port to something different then the standard one in the ts3server.ini it is still using the standard 10011 port and i am unsure why this is.

I am using portainer and have the server query port set to the non standard one for both TCP and UDP as well as in the ts3server.ini.

Other then that thank you very much for this image as it working fine other then this port issue.

**Comment by ertagh** [comment]
I'm very sorry for my late reply!

The server actually starts up using the minimal runscript (therefore it doesn't use the ini file)
Have you edited the minimal runscript so it'll include the inifile at startup?

I will look into the other issue and maybe push an update that will include the usage of an ini file. I will let you know!

Also thanks for the kind words

**Comment by solidus1983** [comment]
I haven't modded the minimal runscript, Just thought i'd point out the issue.
Not sure if you could even parse the Docker network setup into the script however its been running like a dream for me since running the docker container, just that i am using port knocking to get it to the old ports that was in use.

**Comment by ertagh** [comment]
I just pushed an rather "big" update that also added support for the ts3server ini-file..

**Comment by solidus1983** [comment]
Thank you will test it out.

**Comment by solidus1983** [comment]
Right just rebuilt the TS server with your update and can confirm that port settings in ts3server.ini works fine.

On top of that bootup is fast as anything now and CPU usage is very very very low only 1.5% instead of 3-4% smashing work!
