### ISSUE TITLE
Teamspeak 3 Server Crashing

### ISSUE THREAD

**Issue by solidus1983** [ertagh/teamspeak3-server-arm#6]
Hi, since using the dos box version i seem to be having crashing issues.

Looking at the teamspeak 3 server logs i am getting

`|VirtualServerBase|1  |query client disconnected 'serveradmin'(id:1) reason 'reasonmsg=deselected virtualserver'`

Thought it was the Web panel causing the issue so i stopped the container with it on and it was still crashing after with

`Received signal SIGTERM, shutting down.`

nothing else shows in the logs for teamspeak however there is a few errors in the portainer logs for the container.

```
Warning: call to partially implemented dl_iterate_phdr(0x87f3300, 0xf7806f78)
,Warning: call to partially implemented dl_iterate_phdr(0x87f3300, 0xf7806e38)
,Warning: call to partially implemented dl_iterate_phdr(0x87f3300, 0xf7806f68)
,Warning: call to partially implemented dl_iterate_phdr(0x87f3300, 0xf7806e48)
,Warning: call to partially implemented dl_iterate_phdr(0x87f3300, 0xf7806f38)

```

**Comment by ertagh** [comment]
The first message you are getting seems to be from the web panel.
And the last ones are actually from Box86. But these are the warnings I'm mentioning in the readme and doesn't affect the functionality from the server.

The one in the middle is actually the one that would be interesting.. 
But without more information it's hard to take a guess.. intersting would be:
- System you are using
- Operating System
- Are you using the ini-file? If so, can you send me the content?

**Comment by solidus1983** [comment]
Using Ubuntu 20.04 aarch64 on a Raspi 3B+ 1GB Version, with Docker and Portioner 2 CE.

TS3 Ini:

```
machine_id=
default_voice_port=9987
voice_ip=0.0.0.0, ::
licensepath=
filetransfer_port=30033
filetransfer_ip=0.0.0.0, ::
query_port=10011
query_ip=0.0.0.0, ::
query_ip_whitelist=query_ip_whitelist.txt
query_ip_blacklist=query_ip_blacklist.txt
dbplugin=ts3db_sqlite3
dbpluginparameter=
dbsqlpath=sql/
dbsqlcreatepath=create_sqlite/
dbconnections=10
logpath=logs
logquerycommands=0
dbclientkeepdays=30
logappend=0
query_skipbruteforcecheck=0
```
(Changed the ports just incase as its in public domain)

Now currently i am using the Qemu version and its been fine. The Box86 version just kept crashing it would work for a bit then the server would simply crash, forcing me to reboot the container to get it back online only for it to crash again sometime after.

As for the warning i thought i just mention them just incase.

Sorry for the late reply though.

Also just had a thought, but don't think it would cause the issue if the ENV still had

```
ONLY_LOG_FILES 1
INTERVAL 600
```

**Comment by ertagh** [comment]
Did some testing today. It looks like I killed the process to early resulting in an corrupt sql database. Wasn't an problem with the RPi4, maybe because of its performance.

I rewrote that part and tested it with my RPi3b+.. 
It looks like it's working now, so I pushed an update.

Would be nice if you could test and report back

**Comment by solidus1983** [comment]
Thanks for that it crashed tonight as well with a full server of 32.

It was working all day with just me in the server but as soon as a people came on it went.

However nothing in the logs, will test again.


Edit: I am now running the Box86 version and connected 32 clients to the server and disconnected 30 clients all at once, it didn't crash but will keep you upto date if i get any more.

**Comment by ertagh** [comment]
I am honest: I am not able to test how the server behaves under full load.
I can imagine that QEMU runs in some problems, because it actually runs on just one core. With Box86 I have less experience.

**Comment by ertagh** [comment]
Just a little hint: Today I switched back to QEMU in the "latest" tag (because of issue #7 )

**Comment by solidus1983** [comment]
Thanks, it just crashed again anyways with just me in there. Going back to QEMU base image.

Thanks for your help!
