### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by inventory69** [ertagh/teamspeak3-server-arm#7]
Hello, i am using this on my raspberry pi 4b with docker-compose.
I was using it before the change to box86 and everything was working fine.
Now when i add someone to a new servergroup with a new icon, it seems they cannot download it.
Also when i upload a icon from outside my network, it immediatly shows that error: 

> The futex facility returned an unexpected error code.

Then the container stops..

My docker-compose:

teamspeak:
    container_name: teamspeak
    image: ertagh/teamspeak3-server:latest
    #restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011/tcp
      - 30033:30033/tcp
    environment:
      - TIME_ZONE=Europe/Berlin
      - TS_UPDATE=1
    volumes:
      - ${DOCKERCONFDIR}/ts3server:/teamspeak/save/

**Comment by ertagh** [comment]
I tested it and had the same problem. Looks like Box86 isn't as ready as I hoped it to be. 
Should have tested that before actually publishing it.. very sorry about that!

I updated the images now:
-> latest & latest-predownloaded are now again qemu based
-> box86 images are separated
-> reworked the readme to fit that..

Again: I'm very sorry for that! Shouldn't have happend!

Please report back if everything is working again!

**Comment by inventory69** [comment]
Thanks for the quick reply and your time.
I will test it later when my ISP connection returns

**Comment by inventory69** [comment]
Everything is working fine now, thanks :)
