### ISSUE TITLE
After restarting the container /teamspeak/logs seems missing

### ISSUE THREAD

**Issue by bennyzen** [ertagh/teamspeak3-server-arm#9]
Simply restarting the container seems to break things. After a restart, the logs folder seems missing. 

Doing something like `docker logs -f ts3` results in:
```
cat: /teamspeak/logs/: No such file or directory
mv: cannot stat '/teamspeak/logs/': No such file or directory
ls: cannot access '/teamspeak/logs': No such file or directory
```
repeated continously.

The container comes back up, but the logs are gone or just filled with the statements above.

I can't figure out how to fix this, as the logs folder is present and readable .

**Comment by ertagh** [comment]
Hm I can't recreate this error on my side..

Please comment your `docker run` / `docker create` command, so that I can look further into it.

**Comment by bennyzen** [comment]
Funny, but I can't reproduce the issue today either. Something must have changed. But hey, it works now. Thank you for your patience.
